---

# NOTE: only work on rhel derivatives for now

- name: load OS specific variables (see roles/*/vars/*)
  include_vars: "{{ansible_os_family}}.yml"

- name: install network packages
  package: name={{network_pkgs}} state={{network_pkg_state}}

  # install and enable openvswitch only if needed
- include: openvswitch.yml
  when: "('ovsbridge' in network|selectattr('type', 'defined')|map(attribute='type')|list)
   and ((ansible_distribution == "CentOS" and ansible_distribution_major_version|int <= "7") or
        (ansible_distribution != "Centos")))

- name: template /etc/network/interfaces on Debian machines
  template:
    src: "{{ansible_os_family}}_interfaces.j2"
    dest: /etc/network/interfaces
    mode: 0644
  with_items: "{{networks}}"
  when: network is defined and ansible_os_family == 'Debian'
  register: changed_devices
  notify: restart ifaces

- name: template network devices' files
  template:
    src: "{{ansible_os_family}}_device.j2"
    # dash is in 'network_device_file_prefix'
    dest: "{{network_conf_path}}/{{network_device_file_prefix}}{{item.device}}"
    mode: 0644
  with_items: "{{networks}}"
  when: network is defined
  register: changed_devices
  notify: restart ifaces

- name: template the route configuration files for RHEL machines
  template:
    src: "{{ansible_os_family}}_routes.j2"
    dest: "{{network_conf_path}}/route-{{item.device}}"
    mode: 0644
  with_items: "{{networks}}"
  when: network is defined and ansible_os_family == 'RedHat'
  notify: change routes

- incude: debug.yml
  when: network_debug

- include: remove_device_files.yml
  when: network_exclusive_devices

  # get wanted permanently configured static routes
  # ignore errors as file may not exist
  # must be done before we template the file
- name: register permanent system routes
  command: cat {{network_conf_path}}/route-{{item.device}}
  with_items: "{{networks}}"
  ignore_errors: true
  check_mode: true
  register: network_permanent_routes
  when: ansible_os_family != "Debian"
