---

# NOTE: only work on rhel derivatives for now

- name: load OS specific variables (see roles/*/vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: install network packages
  package: name={{ network_packages }} state=latest

- name: template static interface cfg file for RHEL machines
  template:
    src: iface_{{ ansible_os_family }}.j2
    dest: "{{ network_conf_path }}/ifcfg-{{ item.device }}"
    mode: 0644
  with_items: network
  when: network is defined
  register: changed_ifaces
  notify: restart ifaces

- name: template the route configuration file
  template:
    src: route_{{ ansible_os_family }}.j2
    dest: "{{ network_conf_path }}/route-{{ item.device }}"
    mode: 0644
  with_items: network
  # when: routes is defined
  notify: change routes

  # get wanted permanently configured static routes
  # ignore errors as file may not exist
  # must be done before we template the file
- name: register permanent system routes
  command: cat {{ network_conf_path }}/route-{{ item.device }}
  with_items: network
  ignore_errors: true
  always_run: true
  register: network_permanent_routes
