---
# handlers file for network

- name: restart ifaces
  shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: changed_devices.results
  when: item.changed
  # service: name=network state=restarted

- name: del devices
  command: ip link del dev {{ item.item.device }}
  with_items: deleted_ifaces.results
  when: item.changed

  # # edit change iface without restarting interface
# - name: change ip
  # command

- name: change routes
  command: ip route replace {{ item.1 }}
  with_subelements:
    - network_permanent_routes.results
    - stdout_lines
  when: "'default' not in item.1 and 0.0.0.0 not in item.1"

# - name: change routes
#   command: ip route replace
#   with_nested:
#     - network_permanent_routes.stdout_lines
#     - network_permanent_routes
#   when: item.0 not in network_permanent_routes
