---
# handlers file for network

- name: restart ifaces
  shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: changed_ifaces.results
  when: item.changed
  # service: name=network state=restarted
